services:
  vllm-embedding:
    image: vllm/vllm-openai:latest-cu130
    container_name: vllm-embedding
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    networks:
      - vllm
    ports:
      - "8002:8000"
    ipc: host
    volumes:
      - /root/.cache/huggingface:/root/.cache/huggingface
    command: [
        "Qwen/Qwen3-Embedding-0.6B",
        "--port", "8000",
        "--host", "0.0.0.0",
        "--gpu-memory-utilization", "0.1",
        "--max-model-len", "1024"
      ]
    restart: unless-stopped

networks:
  vllm:
    external: true
