"""Write docs/tools.md from the tools this build registers.

    python scripts/tool_docs.py          # rewrite docs/tools.md
    python scripts/tool_docs.py --check  # exit 1 if docs/tools.md is out of date

The page is generated so it cannot drift from the code; tests/test_tool_docs.py
runs the check.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import re
import sys
from pathlib import Path
from typing import Any

from openitcockpit_mcp.config import Settings
from openitcockpit_mcp.server import create_server
from openitcockpit_mcp.toolsets import load, resolve_path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "docs" / "tools.md"


def effect(annotations: dict[str, Any]) -> str:
    if annotations.get("readOnlyHint"):
        return "reads"
    if annotations.get("destructiveHint"):
        return "**changes existing**"
    if annotations.get("idempotentHint"):
        return "**acts**"
    return "**creates**"


def signature(schema: dict[str, Any]) -> str:
    required = schema.get("required", [])
    parts = [f"`{name}`" for name in schema.get("properties", {}) if name in required]
    parts += [f"`{name}?`" for name in schema.get("properties", {}) if name not in required]
    return ", ".join(parts) or "-"


def first_sentence(text: str) -> str:
    """Up to the first full stop that ends a sentence - not one inside "i.e." or "e.g."."""
    text = " ".join((text or "").split())
    match = re.search(r"(?<!\bi\.e)(?<!\be\.g)\.\s+(?=[A-Z`])", text)
    return (text if match is None else text[: match.start() + 1]).replace("|", "\\|")


def render() -> str:
    settings = Settings(mcp_auth_token="docs", apikey="docs-key", baseurl="https://oitc.example.test", enable_write_tools=True)
    mcp, deps = create_server(settings)
    try:
        tools = {tool.name: tool for tool in asyncio.run(mcp.list_tools())}
    finally:
        deps.api.close()

    def size(name: str) -> int:
        tool = tools[name]
        definition = {"name": name, "description": tool.description or "", "parameters": tool.parameters}
        return len(json.dumps(definition, separators=(",", ":"), ensure_ascii=False))

    lines = [
        "# Tools",
        "",
        "<!-- Generated by scripts/tool_docs.py from the registered tools. Do not edit by hand. -->",
        "",
        f"{len(tools)} tools, {sum(1 for t in tools.values() if t.annotations and t.annotations.read_only_hint)} of them read-only. "
        "Tools that change anything are registered only with `OITC_ENABLE_WRITE_TOOLS=true`.",
        "",
        "**Size** is the definition a model receives with every request - name, description and input "
        "schema as compact JSON - in characters. Roughly 3.1 to 3.7 characters make one token; "
        "see [tool-design.md](tool-design.md).",
        "",
    ]

    def table(names: list[str]) -> list[str]:
        rows = ["| Tool | Effect | Parameters | Size | What it is for |", "|---|---|---|---:|---|"]
        for name in names:
            tool = tools[name]
            annotations = tool.annotations.model_dump(by_alias=True, exclude_none=True) if tool.annotations else {}
            rows.append(
                f"| `{name}` | {effect(annotations)} | {signature(tool.parameters)} | {size(name)} | {first_sentence(tool.description or '')} |"
            )
        return rows

    sets = load(resolve_path(None))
    in_a_set: set[str] = set()
    for name, toolset in sets.items():
        members = sorted(tool for tool in toolset.tools if tool in tools)
        in_a_set |= set(members)
        lines += [
            f"## `{name}`",
            "",
            toolset.description,
            "",
            f"{len(members)} tools, {sum(size(tool) for tool in members)} characters.",
            "",
            *table(members),
            "",
        ]

    rest = sorted(set(tools) - in_a_set)
    if rest:
        lines += ["## In no toolset", "", "Reachable with `OITC_TOOLSETS=all` or by naming the tool.", "", *table(rest), ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != content:
            print(f"{TARGET.relative_to(ROOT)} is out of date - run python scripts/tool_docs.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
